name: NodeJS with Webpack

on:
  push:
    branches: [ "ts" ]
  pull_request:
    branches: [ "ts" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm install -D ts-loader
        npx webpack

    - name: Archive Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Webpack Package
        path: |
          dist
          !dist/*.map